import MainFooter from "@/components/Common/MainFooter";
import MainNavbar from "@/components/Common/MainNavbar";
import LanguageThemeToggle from "@/components/Common/LanguageThemeToggle";
import { Roboto, Hind_Siliguri } from "next/font/google";
import "./globals.css";

// Configure Google Fonts
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["300", "400", "500", "700"],
});

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  variable: "--font-hind-siliguri",
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Md Salehin Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${roboto.variable} ${hindSiliguri.variable}`}>
        <MainNavbar />
        <LanguageThemeToggle />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}